spring:
  application:
    name: jms-monitor

---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      enabled: false    # Explicitly disable config server for dev
  data:
    mongodb:
      uri: mongodb://mongodb:27017/jmsmonitor

activemq:
  brokers:
    - name: local-broker
      url: tcp://activemq:61616
      user: admin
      password: admin

---
# PRD: MongoDB and ActiveMQ will be fetched from the config server
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      uri: http://prod-config-server:8888
      fail-fast: true